"""
Final Orchestration Pipeline
============================

End-to-end flow:
parse -> clean -> chunk -> embed -> index

Supports 2 input modes:
1) Local test folder (raw files in infrastructure/storage/raw_documents)
2) Production upload manifest generated by API
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Any, List, Optional
import json
import logging
import sys
import time

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
	sys.path.insert(0, str(PROJECT_ROOT))

from backend.pipelines.post_cleaning_pipeline import (
	PipelineConfig,
	PipelineResult,
	PostCleaningPipeline,
)

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


@dataclass
class FinalPipelineConfig:
	"""Configuration for final pipeline orchestration."""

	project_root: Optional[Path] = None
	use_local_test_folder: bool = True
	upload_manifest_path: Path = field(
		default_factory=lambda: Path("infrastructure/storage/uploads/uploaded_documents.json")
	)

	pipeline: PipelineConfig = field(default_factory=PipelineConfig)


class FinalPipeline:
	"""Coordinates data-source preparation and processing pipeline execution."""

	def __init__(self, config: Optional[FinalPipelineConfig] = None) -> None:
		self.config = config or FinalPipelineConfig()
		self.project_root = (
			Path(self.config.project_root)
			if self.config.project_root
			else PROJECT_ROOT
		)

	def _prepare_uploaded_documents_for_pipeline(self) -> Dict[str, Any]:
		"""
		Convert uploaded manifest records into cleaned JSON expected by merge/chunk stages.
		"""
		manifest_path = self.project_root / self.config.upload_manifest_path
		if not manifest_path.exists():
			logger.warning(f"Upload manifest not found: {manifest_path}")
			return {"uploaded_records_prepared": 0, "reason": "manifest-missing"}

		with open(manifest_path, "r", encoding="utf-8") as f:
			records = json.load(f)

		if not isinstance(records, list) or not records:
			logger.warning("Upload manifest is empty or invalid.")
			return {"uploaded_records_prepared": 0, "reason": "manifest-empty-or-invalid"}

		cleaned_txt_path = self.project_root / self.config.pipeline.processed_dir / "cleaned_txts.json"
		cleaned_txt_path.parent.mkdir(parents=True, exist_ok=True)

		normalized: List[Dict[str, Any]] = []
		for i, record in enumerate(records, start=1):
			content = str(record.get("content", "")).strip()
			if not content:
				continue

			title = record.get("title") or f"uploaded_document_{i}"
			metadata = record.get("metadata") or {}

			normalized.append(
				{
					"id": record.get("id", i),
					"source": record.get("source", "upload"),
					"title": title,
					"content": content,
					"metadata": {
						"char_count": metadata.get("char_count", len(content)),
						"file_path": metadata.get("file_path", "uploaded-via-api"),
					},
				}
			)

		with open(cleaned_txt_path, "w", encoding="utf-8") as f:
			json.dump(normalized, f, indent=2, ensure_ascii=False)

		logger.info(f"Prepared {len(normalized)} uploaded records: {cleaned_txt_path}")
		return {
			"uploaded_records_prepared": len(normalized),
			"cleaned_txt_path": str(cleaned_txt_path),
		}

	def _has_local_input_files(self) -> bool:
		"""Return True when there are local raw files to process."""
		raw_root = self.project_root / self.config.pipeline.raw_dir
		if not raw_root.exists():
			return False

		patterns = ("*.txt", "*.pdf", "*.xml", "*.wav")
		for pattern in patterns:
			if list(raw_root.rglob(pattern)):
				return True
		return False

	def _failure_result(self, errors: List[str], started_at: float) -> PipelineResult:
		"""Build a non-throwing failed pipeline result."""
		return PipelineResult(
			success=False,
			stages_completed=[],
			stages_failed=[],
			output_files={},
			statistics={},
			duration_seconds=round(time.time() - started_at, 3),
			errors=errors,
		)

	def run(self) -> PipelineResult:
		started_at = time.time()
		pipeline_config = self.config.pipeline

		try:
			if self.config.use_local_test_folder:
				logger.info("Using LOCAL TEST FOLDER input mode.")
				if not self._has_local_input_files():
					return self._failure_result(
						[
							"No local raw input files found under infrastructure/storage/raw_documents.",
						],
						started_at,
					)
			else:
				logger.info("Using PRODUCTION UPLOAD input mode.")
				prep = self._prepare_uploaded_documents_for_pipeline()
				if prep.get("uploaded_records_prepared", 0) <= 0:
					reason = prep.get("reason", "unknown")
					return self._failure_result(
						[
							f"No uploaded records prepared for processing (reason: {reason}).",
						],
						started_at,
					)
				pipeline_config.skip_cleaning = True

			pipeline = PostCleaningPipeline(config=pipeline_config, project_root=self.project_root)
			return pipeline.run()
		except Exception as exc:
			logger.exception("FinalPipeline crashed")
			return self._failure_result([f"Final pipeline error: {exc}"], started_at)


if __name__ == "__main__":
	# TESTING MODE (reads from raw_documents/* folders)
	config = FinalPipelineConfig(use_local_test_folder=True)

	# PRODUCTION MODE (enable when frontend upload is wired in deployment)
	# config = FinalPipelineConfig(use_local_test_folder=False)

	result = FinalPipeline(config).run()
	print(f"\n✅ Pipeline {'completed successfully' if result.success else 'completed with errors'}")
	print(f"⏱️ Duration: {result.duration_seconds}s")
	if result.errors:
		print("Errors:")
		for err in result.errors:
			print(f" - {err}")
