import json
from strict_validator import validate_record
from error_report_pdf import generate_report
from pathlib import Path


def run_validation(records, verbose=True):
    """
    Run validation on a list of records.
    
    Args:
        records: List of record dictionaries to validate
        verbose: If True, print detailed logs during validation
    
    Returns:
        tuple: (valid_records, warning_log, error_log)
    """
    valid = []
    error_log = []
    warning_log = []

    if verbose:
        print("\n🚀 Starting strict validation with auto-corrections\n")

    for idx, record in enumerate(records, start=1):
        if verbose:
            print(f"📄 Validating record {idx}")

        is_valid, corrected, warnings, errors = validate_record(record)

        for w in warnings:
            if verbose:
                print(f"⚠ WARNING: {w}")
            warning_log.append({
                "record_index": idx,
                "warning": w
            })

        if errors:
            if verbose:
                print("❌ Errors found:")
                for e in errors:
                    print(f"   - {e}")

            error_log.append({
                "record_index": idx,
                "errors": errors,
                "record": corrected
            })
            if verbose:
                print("➡ User can fix via OLLAMA or skip\n")
        else:
            valid.append(corrected)
            if verbose:
                print("✅ Record is valid\n")

    return valid, warning_log, error_log


if __name__ == "__main__":
    # Load data from default location
    input_file = Path("Pinak's Work") / "jsons" / "final_enriched.json"
    
    if not input_file.exists():
        print(f"❌ Error: {input_file} not found!")
        exit(1)
    
    with open(input_file, "r", encoding="utf-8") as f:
        records = json.load(f)

    valid, warnings, errors = run_validation(records, verbose=True)

    # Save validated records
    output_file = "validated_records.json"
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(valid, f, indent=2)

    # Generate report (try to include a project logo if available)
    def _find_logo():
        root = Path(__file__).resolve().parents[1]
        candidates = [root / 'assets' / 'logo.png', root / 'assets' / 'logo.jpg', root / 'logo.png', root / 'logo.jpg']
        for c in candidates:
            if c.exists():
                return str(c)
        return None

    logo = _find_logo()
    generate_report(warnings, errors, output_file="validation_report", logo_path=logo, watermark_text='Generated by AI Data Transformation Pipeline')

    print("\n📁 Outputs:")
    print(f"• {output_file} ({len(valid)} valid records)")
    print("• validation_report.docx")
    print("• validation_report.pdf (if docx2pdf is installed)")
